-- CreateTable
CREATE TABLE "IOS" (
    "id" TEXT NOT NULL,
    "Name" TEXT NOT NULL,
    "Type" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "userId" TEXT,

    CONSTRAINT "IOS_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "IOS" ADD CONSTRAINT "IOS_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
